language: python
python:
  - "3.5"
  - "3.6"

env:
  - DJANGO_SETTINGS_MODULE="sbadmin.settings.travis"
  - MOZ_HEADLESS=1

addons:
  firefox: latest

# Command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

services:
  - postgresql

script:
  - coverage run --source="." manage.py test -v 2
  - coverage report
  - flake8
