language: python
python:
  - "3.5"
  - "3.6"

# Command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

env: DJANGO_SETTINGS_MODULE="sbadmin.settings.travis"

services:
  - postgresql

script:
  - pipenv run coverage run --source="." manage.py test -v 2
  - pipenv run coverage report
